
#configure 2 vms
Vagrant.configure("2") do |config|

  config.vm.define "app" do |app|
  # configures the vm
    app.vm.box = "ubuntu/bionic64"
    app.vm.network "private_network", ip:"192.168.10.100"

  #Put the app folder from local machine to the VM
    app.vm.synced_folder "app", "/home/vagrant/app"

  #provision the vm to have nginx
    app.vm.provision "shell", path: "prov.sh", privileged: false
  end

  config.vm.define "db" do |db|

    db.vm.box = "ubuntu/bionic64"
    db.vm.network "private_network", ip:"192.168.10.150"
    db.vm.synced_folder "environment", "/home/vagrant/environment"


  end
end